name=input("Please type in a name:")
year=input("Please type in a year:")
print(name+" is a valiant knight, born in the year "+year+".")
print("One morning "+name+" woke up to an awful racket: a dragon was approaching the village.")
print("Only "+name+" could save the village's residents.")